// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: regist.proto

package regist

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RegistClient is the client API for Regist service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistClient interface {
	GetRegist(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*RegistRepose, error)
}

type registClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistClient(cc grpc.ClientConnInterface) RegistClient {
	return &registClient{cc}
}

func (c *registClient) GetRegist(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*RegistRepose, error) {
	out := new(RegistRepose)
	err := c.cc.Invoke(ctx, "/regist.Regist/getRegist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistServer is the server API for Regist service.
// All implementations must embed UnimplementedRegistServer
// for forward compatibility
type RegistServer interface {
	GetRegist(context.Context, *IdRequest) (*RegistRepose, error)
	mustEmbedUnimplementedRegistServer()
}

// UnimplementedRegistServer must be embedded to have forward compatible implementations.
type UnimplementedRegistServer struct {
}

func (UnimplementedRegistServer) GetRegist(context.Context, *IdRequest) (*RegistRepose, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegist not implemented")
}
func (UnimplementedRegistServer) mustEmbedUnimplementedRegistServer() {}

// UnsafeRegistServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistServer will
// result in compilation errors.
type UnsafeRegistServer interface {
	mustEmbedUnimplementedRegistServer()
}

func RegisterRegistServer(s grpc.ServiceRegistrar, srv RegistServer) {
	s.RegisterService(&Regist_ServiceDesc, srv)
}

func _Regist_GetRegist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistServer).GetRegist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/regist.Regist/getRegist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistServer).GetRegist(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Regist_ServiceDesc is the grpc.ServiceDesc for Regist service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Regist_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "regist.Regist",
	HandlerType: (*RegistServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getRegist",
			Handler:    _Regist_GetRegist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "regist.proto",
}
