// Code generated by goctl. DO NOT EDIT!
// Source: regist.proto

package server

import (
	"context"

	"zero-study/mall/regist/rpc/internal/logic"
	"zero-study/mall/regist/rpc/internal/svc"
	"zero-study/mall/regist/rpc/types/regist"
)

type RegistServer struct {
	svcCtx *svc.ServiceContext
	regist.UnimplementedRegistServer
}

func NewRegistServer(svcCtx *svc.ServiceContext) *RegistServer {
	return &RegistServer{
		svcCtx: svcCtx,
	}
}

func (s *RegistServer) GetRegist(ctx context.Context, in *regist.IdRequest) (*regist.RegistRepose, error) {
	l := logic.NewGetRegistLogic(ctx, s.svcCtx)
	return l.GetRegist(in)
}
