// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Id string `path:"id"`
}

type LoginReply struct {
	Id      string `json:"id"`
	Account string `json:"account"`
	Pwd     string `json:"pwd"`
}
